---

enable_logging:   False
dask_workers:     4
bucket:           'eis-dh-hydro'
input_path:       'LIS_NETCDF/DA_10km/DA_LAI_PMW_THySM_HyMAP/SURFACEMODEL/**/LIS_HIST*.nc'
target_path:      'LIS/DA_10km/RECHUNKED/DA_LAI_PMW_THySM_HyMAP/SURFACEMODEL/LIS_HIST.d01.zarr'
target_chunks:    {'time': 6}
inputs_per_chunk: 6
nitems_per_file:  1
temp_dir:         '/home/jovyan/efs/tmp'