---

enable_logging:   False
dask_workers:     4
bucket:           'eis-dh-hydro'
input_path:       'LIS_NETCDF/DELTA_2km/9SEA_RA_MAN_LAKE/ROUTING/**/LIS_HIST*.nc'
target_path:      'LIS/DELTA_2km/9SEA_RA_MAN_LAKE/ROUTING/LIS_HIST_100mb_chunks.d01.zarr'
target_chunks:    {'time': 20}
inputs_per_chunk: 20
nitems_per_file:  1
temp_dir:         '/home/jovyan/efs/tmp'
