---

enable_logging:   False
dask_workers:     4
bucket:           'eis-dh-hydro'
input_path:       'LIS_NETCDF/OL_1km/MERRA_IMERG/SURFACEMODEL/**/LIS_HIST*.nc'
target_path:      'LIS/OL_1km/2000_2021/MERRA_IMERG/LIS_HIST_rechunked.d01.zarr'
target_chunks:    {'time': 1, 'lon': 200, 'lat': 200}
inputs_per_chunk: 1
nitems_per_file:  1
temp_dir:         '/home/jovyan/efs/tmp'